// Code generated by query-table-codegen. DO NOT EDIT.
package archive

import querytable "github.com/Pythia-Software/query-table/backends/go"

func PharosActivitySchema() querytable.Schema {
	return querytable.Schema{
		Name:    "pharos_activity",
		IDField: "id",
		Fields: map[string]querytable.FieldSpec{
			"id":                {Name: "id", Kind: querytable.FieldText, Expr: "r.\"id\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"id\""},
			"state":             {Name: "state", Kind: querytable.FieldEnum, Expr: "r.\"state\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"state\""},
			"sources":           {Name: "sources", Kind: querytable.FieldTextArray, Expr: "r.\"sources\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"sources\""},
			"current_source":    {Name: "current_source", Kind: querytable.FieldText, Expr: "r.\"current_source\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"current_source\""},
			"phase":             {Name: "phase", Kind: querytable.FieldEnum, Expr: "r.\"phase\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"phase\""},
			"progress":          {Name: "progress", Kind: querytable.FieldNumber, Expr: "r.\"progress\"", Synthetic: false, ExpressionNumeric: true, Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"progress\""},
			"completed_sources": {Name: "completed_sources", Kind: querytable.FieldNumber, Expr: "r.\"completed_sources\"", Synthetic: false, ExpressionNumeric: true, Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"completed_sources\""},
			"total_sources":     {Name: "total_sources", Kind: querytable.FieldNumber, Expr: "r.\"total_sources\"", Synthetic: false, ExpressionNumeric: true, Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"total_sources\""},
			"workspaces":        {Name: "workspaces", Kind: querytable.FieldNumber, Expr: "r.\"workspaces\"", Synthetic: false, ExpressionNumeric: true, Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"workspaces\""},
			"conversations":     {Name: "conversations", Kind: querytable.FieldNumber, Expr: "r.\"conversations\"", Synthetic: false, ExpressionNumeric: true, Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"conversations\""},
			"messages":          {Name: "messages", Kind: querytable.FieldNumber, Expr: "r.\"messages\"", Synthetic: false, ExpressionNumeric: true, Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"messages\""},
			"started_at":        {Name: "started_at", Kind: querytable.FieldDatetime, Expr: "r.\"started_at\"", Synthetic: false, SQLiteDatetimeFormat: "rfc3339", Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"started_at\""},
			"updated_at":        {Name: "updated_at", Kind: querytable.FieldDatetime, Expr: "r.\"updated_at\"", Synthetic: false, SQLiteDatetimeFormat: "rfc3339", Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"updated_at\""},
			"completed_at":      {Name: "completed_at", Kind: querytable.FieldDatetime, Expr: "r.\"completed_at\"", Synthetic: false, SQLiteDatetimeFormat: "rfc3339", Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"completed_at\""},
			"error":             {Name: "error", Kind: querytable.FieldText, Expr: "r.\"error\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"error\""},
			"result_summary":    {Name: "result_summary", Kind: querytable.FieldText, Expr: "r.\"result_summary\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"result_summary\""},
		},
		DefaultSort:  []querytable.OrderBy{{Field: "started_at", Dir: "desc", Nulls: "last"}},
		TiebreakSort: []querytable.OrderBy{{Field: "id", Dir: "asc"}},
	}
}
