// Code generated by query-table-codegen. DO NOT EDIT.
package archive

import querytable "github.com/Pythia-Software/query-table/backends/go"

func PharosLibrarySchema() querytable.Schema {
	return querytable.Schema{
		Name:    "pharos_library",
		IDField: "id",
		Fields: map[string]querytable.FieldSpec{
			"id":                        {Name: "id", Kind: querytable.FieldText, Expr: "r.\"id\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"id\""},
			"title":                     {Name: "title", Kind: querytable.FieldText, Expr: "r.\"title\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"title\""},
			"repository_name":           {Name: "repository_name", Kind: querytable.FieldText, Expr: "r.\"repository_name\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"repository_name\""},
			"source_kind":               {Name: "source_kind", Kind: querytable.FieldEnum, Expr: "r.\"source_kind\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"source_kind\""},
			"activity_at":               {Name: "activity_at", Kind: querytable.FieldDatetime, Expr: "r.\"activity_at\"", Synthetic: false, SQLiteDatetimeFormat: "rfc3339", Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"activity_at\""},
			"purpose":                   {Name: "purpose", Kind: querytable.FieldText, Expr: "r.\"purpose\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"purpose\""},
			"outcome":                   {Name: "outcome", Kind: querytable.FieldText, Expr: "r.\"outcome\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"outcome\""},
			"branch":                    {Name: "branch", Kind: querytable.FieldText, Expr: "r.\"branch\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"branch\""},
			"owner":                     {Name: "owner", Kind: querytable.FieldText, Expr: "r.\"owner\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"owner\""},
			"flavor":                    {Name: "flavor", Kind: querytable.FieldText, Expr: "r.\"flavor\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"flavor\""},
			"version":                   {Name: "version", Kind: querytable.FieldText, Expr: "r.\"version\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"version\""},
			"lifecycle":                 {Name: "lifecycle", Kind: querytable.FieldEnum, Expr: "r.\"lifecycle\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"lifecycle\""},
			"preservation_completeness": {Name: "preservation_completeness", Kind: querytable.FieldEnum, Expr: "r.\"preservation_completeness\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"preservation_completeness\""},
			"conversation_count":        {Name: "conversation_count", Kind: querytable.FieldNumber, Expr: "r.\"conversation_count\"", Synthetic: false, ExpressionNumeric: true, Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"conversation_count\""},
			"turn_count":                {Name: "turn_count", Kind: querytable.FieldNumber, Expr: "r.\"turn_count\"", Synthetic: false, ExpressionNumeric: true, Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"turn_count\""},
			"token_count":               {Name: "token_count", Kind: querytable.FieldNumber, Expr: "r.\"token_count\"", Synthetic: false, ExpressionNumeric: true, Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"token_count\""},
			"cost_usd":                  {Name: "cost_usd", Kind: querytable.FieldNumber, Expr: "r.\"cost_usd\"", Synthetic: false, ExpressionNumeric: true, Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"cost_usd\""},
			"cost_today_usd":            {Name: "cost_today_usd", Kind: querytable.FieldNumber, Expr: "r.\"cost_today_usd\"", Synthetic: false, ExpressionNumeric: true, Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"cost_today_usd\""},
			"price_status":              {Name: "price_status", Kind: querytable.FieldEnum, Expr: "r.\"price_status\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"price_status\""},
			"tool_use_count":            {Name: "tool_use_count", Kind: querytable.FieldNumber, Expr: "r.\"tool_use_count\"", Synthetic: false, ExpressionNumeric: true, Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"tool_use_count\""},
			"tool_error_count":          {Name: "tool_error_count", Kind: querytable.FieldNumber, Expr: "r.\"tool_error_count\"", Synthetic: false, ExpressionNumeric: true, Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"tool_error_count\""},
			"compaction_count":          {Name: "compaction_count", Kind: querytable.FieldNumber, Expr: "r.\"compaction_count\"", Synthetic: false, ExpressionNumeric: true, Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"compaction_count\""},
			"subagent_count":            {Name: "subagent_count", Kind: querytable.FieldNumber, Expr: "r.\"subagent_count\"", Synthetic: false, ExpressionNumeric: true, Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"subagent_count\""},
			"subagent_depth":            {Name: "subagent_depth", Kind: querytable.FieldNumber, Expr: "r.\"subagent_depth\"", Synthetic: false, ExpressionNumeric: true, Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"subagent_depth\""},
			"pr_count":                  {Name: "pr_count", Kind: querytable.FieldNumber, Expr: "r.\"pr_count\"", Synthetic: false, ExpressionNumeric: true, Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"pr_count\""},
			"branch_count":              {Name: "branch_count", Kind: querytable.FieldNumber, Expr: "r.\"branch_count\"", Synthetic: false, ExpressionNumeric: true, Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"branch_count\""},
			"file_edit_count":           {Name: "file_edit_count", Kind: querytable.FieldNumber, Expr: "r.\"file_edit_count\"", Synthetic: false, ExpressionNumeric: true, Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"file_edit_count\""},
			"changed_file_count":        {Name: "changed_file_count", Kind: querytable.FieldNumber, Expr: "r.\"changed_file_count\"", Synthetic: false, ExpressionNumeric: true, Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"changed_file_count\""},
			"pr_numbers":                {Name: "pr_numbers", Kind: querytable.FieldText, Expr: "r.\"pr_numbers\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"pr_numbers\""},
			"main_merge_title":          {Name: "main_merge_title", Kind: querytable.FieldText, Expr: "r.\"main_merge_title\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"main_merge_title\""},
			"providers":                 {Name: "providers", Kind: querytable.FieldText, Expr: "r.\"providers\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"providers\""},
			"harnesses":                 {Name: "harnesses", Kind: querytable.FieldText, Expr: "r.\"harnesses\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"harnesses\""},
			"harness_versions":          {Name: "harness_versions", Kind: querytable.FieldText, Expr: "r.\"harness_versions\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"harness_versions\""},
			"models":                    {Name: "models", Kind: querytable.FieldText, Expr: "r.\"models\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"models\""},
			"changed_files":             {Name: "changed_files", Kind: querytable.FieldText, Expr: "r.\"changed_files\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"changed_files\""},
			"error_types":               {Name: "error_types", Kind: querytable.FieldText, Expr: "r.\"error_types\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"error_types\""},
			"location":                  {Name: "location", Kind: querytable.FieldText, Expr: "r.\"location\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"location\""},
		},
		DefaultSort:  []querytable.OrderBy{{Field: "activity_at", Dir: "desc", Nulls: "last"}},
		TiebreakSort: []querytable.OrderBy{{Field: "id", Dir: "asc"}},
	}
}
