// Code generated by query-table-codegen. DO NOT EDIT.
package archive

import querytable "github.com/Pythia-Software/query-table/backends/go"

func PharosMcpCallsSchema() querytable.Schema {
	return querytable.Schema{
		Name:    "pharos_mcp_calls",
		IDField: "id",
		Fields: map[string]querytable.FieldSpec{
			"id":                      {Name: "id", Kind: querytable.FieldNumber, Expr: "r.\"id\"", Synthetic: false, ExpressionNumeric: true, AggregateOps: []string{}, Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"id\""},
			"called_at":               {Name: "called_at", Kind: querytable.FieldDatetime, Expr: "r.\"called_at\"", Synthetic: false, SQLiteDatetimeFormat: "rfc3339", Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"called_at\""},
			"day":                     {Name: "day", Kind: querytable.FieldText, Expr: "r.\"day\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"day\""},
			"week":                    {Name: "week", Kind: querytable.FieldText, Expr: "r.\"week\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"week\""},
			"month":                   {Name: "month", Kind: querytable.FieldText, Expr: "r.\"month\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"month\""},
			"tool_name":               {Name: "tool_name", Kind: querytable.FieldText, Expr: "r.\"tool_name\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"tool_name\""},
			"status":                  {Name: "status", Kind: querytable.FieldEnum, Expr: "r.\"status\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"status\""},
			"arguments_json":          {Name: "arguments_json", Kind: querytable.FieldText, Expr: "r.\"arguments_json\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"arguments_json\""},
			"error_text":              {Name: "error_text", Kind: querytable.FieldText, Expr: "r.\"error_text\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"error_text\""},
			"duration_ms":             {Name: "duration_ms", Kind: querytable.FieldNumber, Expr: "r.\"duration_ms\"", Synthetic: false, ExpressionNumeric: true, Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"duration_ms\""},
			"response_bytes":          {Name: "response_bytes", Kind: querytable.FieldNumber, Expr: "r.\"response_bytes\"", Synthetic: false, ExpressionNumeric: true, Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"response_bytes\""},
			"estimated_output_tokens": {Name: "estimated_output_tokens", Kind: querytable.FieldNumber, Expr: "r.\"estimated_output_tokens\"", Synthetic: false, ExpressionNumeric: true, Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"estimated_output_tokens\""},
			"result_count":            {Name: "result_count", Kind: querytable.FieldNumber, Expr: "r.\"result_count\"", Synthetic: false, ExpressionNumeric: true, Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"result_count\""},
			"truncated":               {Name: "truncated", Kind: querytable.FieldBool, Expr: "r.\"truncated\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"truncated\""},
			"call_count":              {Name: "call_count", Kind: querytable.FieldNumber, Expr: "r.\"call_count\"", Synthetic: false, ExpressionNumeric: true, Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"call_count\""},
			"error_count":             {Name: "error_count", Kind: querytable.FieldNumber, Expr: "r.\"error_count\"", Synthetic: false, ExpressionNumeric: true, Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"error_count\""},
			"truncated_count":         {Name: "truncated_count", Kind: querytable.FieldNumber, Expr: "r.\"truncated_count\"", Synthetic: false, ExpressionNumeric: true, Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"truncated_count\""},
		},
		DefaultSort:  []querytable.OrderBy{{Field: "called_at", Dir: "desc"}},
		TiebreakSort: []querytable.OrderBy{{Field: "id", Dir: "desc"}},
	}
}
