// Code generated by query-table-codegen. DO NOT EDIT.
package archive

import querytable "github.com/Pythia-Software/query-table/backends/go"

func PharosSkillUsagesSchema() querytable.Schema {
	return querytable.Schema{
		Name:    "pharos_skill_usages",
		IDField: "id",
		Fields: map[string]querytable.FieldSpec{
			"id":                  {Name: "id", Kind: querytable.FieldText, Expr: "r.\"id\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"id\""},
			"created_at":          {Name: "created_at", Kind: querytable.FieldDatetime, Expr: "r.\"created_at\"", Synthetic: false, SQLiteDatetimeFormat: "utc-millis", Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"created_at\""},
			"day":                 {Name: "day", Kind: querytable.FieldText, Expr: "r.\"day\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"day\""},
			"week":                {Name: "week", Kind: querytable.FieldText, Expr: "r.\"week\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"week\""},
			"month":               {Name: "month", Kind: querytable.FieldText, Expr: "r.\"month\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"month\""},
			"skill_name":          {Name: "skill_name", Kind: querytable.FieldText, Expr: "r.\"skill_name\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"skill_name\""},
			"skill_path":          {Name: "skill_path", Kind: querytable.FieldText, Expr: "r.\"skill_path\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"skill_path\""},
			"evidence_type":       {Name: "evidence_type", Kind: querytable.FieldEnum, Expr: "r.\"evidence_type\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"evidence_type\""},
			"status":              {Name: "status", Kind: querytable.FieldEnum, Expr: "r.\"status\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"status\""},
			"content_bytes":       {Name: "content_bytes", Kind: querytable.FieldNumber, Expr: "r.\"content_bytes\"", Synthetic: false, ExpressionNumeric: true, Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"content_bytes\""},
			"provider":            {Name: "provider", Kind: querytable.FieldText, Expr: "r.\"provider\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"provider\""},
			"source_kind":         {Name: "source_kind", Kind: querytable.FieldText, Expr: "r.\"source_kind\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"source_kind\""},
			"model":               {Name: "model", Kind: querytable.FieldText, Expr: "r.\"model\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"model\""},
			"repository_name":     {Name: "repository_name", Kind: querytable.FieldText, Expr: "r.\"repository_name\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"repository_name\""},
			"title":               {Name: "title", Kind: querytable.FieldText, Expr: "r.\"title\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"title\""},
			"session_kind":        {Name: "session_kind", Kind: querytable.FieldText, Expr: "r.\"session_kind\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"session_kind\""},
			"tool_name":           {Name: "tool_name", Kind: querytable.FieldText, Expr: "r.\"tool_name\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"tool_name\""},
			"mcp_server":          {Name: "mcp_server", Kind: querytable.FieldText, Expr: "r.\"mcp_server\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"mcp_server\""},
			"mcp_method":          {Name: "mcp_method", Kind: querytable.FieldText, Expr: "r.\"mcp_method\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"mcp_method\""},
			"agent_depth":         {Name: "agent_depth", Kind: querytable.FieldNumber, Expr: "r.\"agent_depth\"", Synthetic: false, ExpressionNumeric: true, Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"agent_depth\""},
			"workspace_id":        {Name: "workspace_id", Kind: querytable.FieldText, Expr: "r.\"workspace_id\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"workspace_id\""},
			"conversation_id":     {Name: "conversation_id", Kind: querytable.FieldText, Expr: "r.\"conversation_id\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"conversation_id\""},
			"tool_call_id":        {Name: "tool_call_id", Kind: querytable.FieldText, Expr: "r.\"tool_call_id\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"tool_call_id\""},
			"evidence_message_id": {Name: "evidence_message_id", Kind: querytable.FieldText, Expr: "r.\"evidence_message_id\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"evidence_message_id\""},
			"body_message_id":     {Name: "body_message_id", Kind: querytable.FieldText, Expr: "r.\"body_message_id\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"body_message_id\""},
		},
		DefaultSort:  []querytable.OrderBy{{Field: "created_at", Dir: "desc", Nulls: "last"}},
		TiebreakSort: []querytable.OrderBy{{Field: "id", Dir: "asc"}},
	}
}
