// Code generated by query-table-codegen. DO NOT EDIT.
package archive

import querytable "github.com/Pythia-Software/query-table/backends/go"

func PharosUsageSchema() querytable.Schema {
	return querytable.Schema{
		Name:    "pharos_usage",
		IDField: "id",
		Fields: map[string]querytable.FieldSpec{
			"id":                             {Name: "id", Kind: querytable.FieldText, Expr: "r.\"id\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"id\""},
			"day":                            {Name: "day", Kind: querytable.FieldText, Expr: "r.\"day\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"day\""},
			"hour":                           {Name: "hour", Kind: querytable.FieldText, Expr: "r.\"hour\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"hour\""},
			"week":                           {Name: "week", Kind: querytable.FieldText, Expr: "r.\"week\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"week\""},
			"month":                          {Name: "month", Kind: querytable.FieldText, Expr: "r.\"month\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"month\""},
			"first_usage_at":                 {Name: "first_usage_at", Kind: querytable.FieldDatetime, Expr: "r.\"first_usage_at\"", Synthetic: false, SQLiteDatetimeFormat: "rfc3339", Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"first_usage_at\""},
			"last_usage_at":                  {Name: "last_usage_at", Kind: querytable.FieldDatetime, Expr: "r.\"last_usage_at\"", Synthetic: false, SQLiteDatetimeFormat: "rfc3339", Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"last_usage_at\""},
			"repository_name":                {Name: "repository_name", Kind: querytable.FieldText, Expr: "r.\"repository_name\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"repository_name\""},
			"provider":                       {Name: "provider", Kind: querytable.FieldEnum, Expr: "r.\"provider\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"provider\""},
			"model_family":                   {Name: "model_family", Kind: querytable.FieldText, Expr: "r.\"model_family\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"model_family\""},
			"model":                          {Name: "model", Kind: querytable.FieldText, Expr: "r.\"model\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"model\""},
			"source_kind":                    {Name: "source_kind", Kind: querytable.FieldEnum, Expr: "r.\"source_kind\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"source_kind\""},
			"harness":                        {Name: "harness", Kind: querytable.FieldText, Expr: "r.\"harness\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"harness\""},
			"harness_version_first":          {Name: "harness_version_first", Kind: querytable.FieldText, Expr: "r.\"harness_version_first\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"harness_version_first\""},
			"harness_version_last":           {Name: "harness_version_last", Kind: querytable.FieldText, Expr: "r.\"harness_version_last\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"harness_version_last\""},
			"harness_version_source":         {Name: "harness_version_source", Kind: querytable.FieldText, Expr: "r.\"harness_version_source\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"harness_version_source\""},
			"session_kind":                   {Name: "session_kind", Kind: querytable.FieldEnum, Expr: "r.\"session_kind\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"session_kind\""},
			"depth":                          {Name: "depth", Kind: querytable.FieldNumber, Expr: "r.\"depth\"", Synthetic: false, ExpressionNumeric: true, Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"depth\""},
			"title":                          {Name: "title", Kind: querytable.FieldText, Expr: "r.\"title\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"title\""},
			"total_tokens":                   {Name: "total_tokens", Kind: querytable.FieldNumber, Expr: "r.\"total_tokens\"", Synthetic: false, ExpressionNumeric: true, Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"total_tokens\""},
			"input_tokens":                   {Name: "input_tokens", Kind: querytable.FieldNumber, Expr: "r.\"input_tokens\"", Synthetic: false, ExpressionNumeric: true, Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"input_tokens\""},
			"uncached_input_tokens":          {Name: "uncached_input_tokens", Kind: querytable.FieldNumber, Expr: "r.\"uncached_input_tokens\"", Synthetic: false, ExpressionNumeric: true, Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"uncached_input_tokens\""},
			"cache_read_input_tokens":        {Name: "cache_read_input_tokens", Kind: querytable.FieldNumber, Expr: "r.\"cache_read_input_tokens\"", Synthetic: false, ExpressionNumeric: true, Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"cache_read_input_tokens\""},
			"cache_creation_input_tokens":    {Name: "cache_creation_input_tokens", Kind: querytable.FieldNumber, Expr: "r.\"cache_creation_input_tokens\"", Synthetic: false, ExpressionNumeric: true, Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"cache_creation_input_tokens\""},
			"cache_creation_5m_input_tokens": {Name: "cache_creation_5m_input_tokens", Kind: querytable.FieldNumber, Expr: "r.\"cache_creation_5m_input_tokens\"", Synthetic: false, ExpressionNumeric: true, Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"cache_creation_5m_input_tokens\""},
			"cache_creation_1h_input_tokens": {Name: "cache_creation_1h_input_tokens", Kind: querytable.FieldNumber, Expr: "r.\"cache_creation_1h_input_tokens\"", Synthetic: false, ExpressionNumeric: true, Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"cache_creation_1h_input_tokens\""},
			"output_tokens":                  {Name: "output_tokens", Kind: querytable.FieldNumber, Expr: "r.\"output_tokens\"", Synthetic: false, ExpressionNumeric: true, Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"output_tokens\""},
			"reasoning_output_tokens":        {Name: "reasoning_output_tokens", Kind: querytable.FieldNumber, Expr: "r.\"reasoning_output_tokens\"", Synthetic: false, ExpressionNumeric: true, Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"reasoning_output_tokens\""},
			"unclassified_tokens":            {Name: "unclassified_tokens", Kind: querytable.FieldNumber, Expr: "r.\"unclassified_tokens\"", Synthetic: false, ExpressionNumeric: true, Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"unclassified_tokens\""},
			"cost_usd":                       {Name: "cost_usd", Kind: querytable.FieldNumber, Expr: "r.\"cost_usd\"", Synthetic: false, ExpressionNumeric: true, Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"cost_usd\""},
			"cost_today_usd":                 {Name: "cost_today_usd", Kind: querytable.FieldNumber, Expr: "r.\"cost_today_usd\"", Synthetic: false, ExpressionNumeric: true, Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"cost_today_usd\""},
			"price_status":                   {Name: "price_status", Kind: querytable.FieldEnum, Expr: "r.\"price_status\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"price_status\""},
			"priced_model":                   {Name: "priced_model", Kind: querytable.FieldText, Expr: "r.\"priced_model\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"priced_model\""},
			"cache_read_share":               {Name: "cache_read_share", Kind: querytable.FieldNumber, Expr: "r.\"cache_read_share\"", Synthetic: false, ExpressionNumeric: true, AggregateOps: []string{}, Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"cache_read_share\""},
			"attribution":                    {Name: "attribution", Kind: querytable.FieldEnum, Expr: "r.\"attribution\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"attribution\""},
			"workspace_id":                   {Name: "workspace_id", Kind: querytable.FieldText, Expr: "r.\"workspace_id\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"workspace_id\""},
			"conversation_id":                {Name: "conversation_id", Kind: querytable.FieldText, Expr: "r.\"conversation_id\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"conversation_id\""},
			"agent_session_id":               {Name: "agent_session_id", Kind: querytable.FieldText, Expr: "r.\"agent_session_id\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"agent_session_id\""},
		},
		DefaultSort:  []querytable.OrderBy{{Field: "day", Dir: "desc", Nulls: "last"}, {Field: "total_tokens", Dir: "desc"}},
		TiebreakSort: []querytable.OrderBy{{Field: "id", Dir: "asc"}},
	}
}
