// Code generated by query-table-codegen. DO NOT EDIT.
package archive

import querytable "github.com/Pythia-Software/query-table/backends/go"

func PharosWritingSchema() querytable.Schema {
	return querytable.Schema{
		Name:    "pharos_writing",
		IDField: "id",
		Fields: map[string]querytable.FieldSpec{
			"id":                  {Name: "id", Kind: querytable.FieldText, Expr: "r.\"id\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"id\""},
			"title":               {Name: "title", Kind: querytable.FieldText, Expr: "r.\"title\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"title\""},
			"repository_name":     {Name: "repository_name", Kind: querytable.FieldText, Expr: "r.\"repository_name\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"repository_name\""},
			"source_kind":         {Name: "source_kind", Kind: querytable.FieldEnum, Expr: "r.\"source_kind\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"source_kind\""},
			"providers":           {Name: "providers", Kind: querytable.FieldText, Expr: "r.\"providers\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"providers\""},
			"first_message_at":    {Name: "first_message_at", Kind: querytable.FieldDatetime, Expr: "r.\"first_message_at\"", Synthetic: false, SQLiteDatetimeFormat: "rfc3339", Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"first_message_at\""},
			"last_message_at":     {Name: "last_message_at", Kind: querytable.FieldDatetime, Expr: "r.\"last_message_at\"", Synthetic: false, SQLiteDatetimeFormat: "rfc3339", Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"last_message_at\""},
			"typed_words":         {Name: "typed_words", Kind: querytable.FieldNumber, Expr: "r.\"typed_words\"", Synthetic: false, ExpressionNumeric: true, Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"typed_words\""},
			"typed_turns":         {Name: "typed_turns", Kind: querytable.FieldNumber, Expr: "r.\"typed_turns\"", Synthetic: false, ExpressionNumeric: true, Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"typed_turns\""},
			"user_turns":          {Name: "user_turns", Kind: querytable.FieldNumber, Expr: "r.\"user_turns\"", Synthetic: false, ExpressionNumeric: true, Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"user_turns\""},
			"typed_share":         {Name: "typed_share", Kind: querytable.FieldNumber, Expr: "r.\"typed_share\"", Synthetic: false, ExpressionNumeric: true, AggregateOps: []string{}, Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"typed_share\""},
			"avg_typed_words":     {Name: "avg_typed_words", Kind: querytable.FieldNumber, Expr: "r.\"avg_typed_words\"", Synthetic: false, ExpressionNumeric: true, AggregateOps: []string{}, Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"avg_typed_words\""},
			"longest_typed_words": {Name: "longest_typed_words", Kind: querytable.FieldNumber, Expr: "r.\"longest_typed_words\"", Synthetic: false, ExpressionNumeric: true, Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"longest_typed_words\""},
			"pasted_words":        {Name: "pasted_words", Kind: querytable.FieldNumber, Expr: "r.\"pasted_words\"", Synthetic: false, ExpressionNumeric: true, Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"pasted_words\""},
			"copied_words":        {Name: "copied_words", Kind: querytable.FieldNumber, Expr: "r.\"copied_words\"", Synthetic: false, ExpressionNumeric: true, Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"copied_words\""},
			"prompt_words":        {Name: "prompt_words", Kind: querytable.FieldNumber, Expr: "r.\"prompt_words\"", Synthetic: false, ExpressionNumeric: true, Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"prompt_words\""},
			"machine_words":       {Name: "machine_words", Kind: querytable.FieldNumber, Expr: "r.\"machine_words\"", Synthetic: false, ExpressionNumeric: true, Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"machine_words\""},
			"user_words":          {Name: "user_words", Kind: querytable.FieldNumber, Expr: "r.\"user_words\"", Synthetic: false, ExpressionNumeric: true, Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"user_words\""},
			"quoted_words":        {Name: "quoted_words", Kind: querytable.FieldNumber, Expr: "r.\"quoted_words\"", Synthetic: false, ExpressionNumeric: true, Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"quoted_words\""},
			"resent_words":        {Name: "resent_words", Kind: querytable.FieldNumber, Expr: "r.\"resent_words\"", Synthetic: false, ExpressionNumeric: true, Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"resent_words\""},
			"template_words":      {Name: "template_words", Kind: querytable.FieldNumber, Expr: "r.\"template_words\"", Synthetic: false, ExpressionNumeric: true, Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"template_words\""},
			"attachment_words":    {Name: "attachment_words", Kind: querytable.FieldNumber, Expr: "r.\"attachment_words\"", Synthetic: false, ExpressionNumeric: true, Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"attachment_words\""},
			"harness_words":       {Name: "harness_words", Kind: querytable.FieldNumber, Expr: "r.\"harness_words\"", Synthetic: false, ExpressionNumeric: true, Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"harness_words\""},
			"automated_words":     {Name: "automated_words", Kind: querytable.FieldNumber, Expr: "r.\"automated_words\"", Synthetic: false, ExpressionNumeric: true, Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"automated_words\""},
			"total_tokens":        {Name: "total_tokens", Kind: querytable.FieldNumber, Expr: "r.\"total_tokens\"", Synthetic: false, ExpressionNumeric: true, Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"total_tokens\""},
			"cost_usd":            {Name: "cost_usd", Kind: querytable.FieldNumber, Expr: "r.\"cost_usd\"", Synthetic: false, ExpressionNumeric: true, Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"cost_usd\""},
			"cost_today_usd":      {Name: "cost_today_usd", Kind: querytable.FieldNumber, Expr: "r.\"cost_today_usd\"", Synthetic: false, ExpressionNumeric: true, Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"cost_today_usd\""},
			"price_status":        {Name: "price_status", Kind: querytable.FieldEnum, Expr: "r.\"price_status\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"price_status\""},
			"typed_per_mtok":      {Name: "typed_per_mtok", Kind: querytable.FieldNumber, Expr: "r.\"typed_per_mtok\"", Synthetic: false, ExpressionNumeric: true, AggregateOps: []string{}, Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"typed_per_mtok\""},
			"subagent_works":      {Name: "subagent_works", Kind: querytable.FieldNumber, Expr: "r.\"subagent_works\"", Synthetic: false, ExpressionNumeric: true, Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"subagent_works\""},
			"launched_works":      {Name: "launched_works", Kind: querytable.FieldNumber, Expr: "r.\"launched_works\"", Synthetic: false, ExpressionNumeric: true, Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"launched_works\""},
		},
		DefaultSort:  []querytable.OrderBy{{Field: "typed_words", Dir: "desc"}},
		TiebreakSort: []querytable.OrderBy{{Field: "id", Dir: "asc"}},
	}
}
