// Code generated by query-table-codegen. DO NOT EDIT.
package archive

import querytable "github.com/Pythia-Software/query-table/backends/go"

func PharosWritingMessagesSchema() querytable.Schema {
	return querytable.Schema{
		Name:    "pharos_writing_messages",
		IDField: "id",
		Fields: map[string]querytable.FieldSpec{
			"id":               {Name: "id", Kind: querytable.FieldText, Expr: "r.\"id\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"id\""},
			"sent_at":          {Name: "sent_at", Kind: querytable.FieldDatetime, Expr: "r.\"sent_at\"", Synthetic: false, SQLiteDatetimeFormat: "utc-millis", Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"sent_at\""},
			"day":              {Name: "day", Kind: querytable.FieldText, Expr: "r.\"day\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"day\""},
			"week":             {Name: "week", Kind: querytable.FieldText, Expr: "r.\"week\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"week\""},
			"month":            {Name: "month", Kind: querytable.FieldText, Expr: "r.\"month\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"month\""},
			"text":             {Name: "text", Kind: querytable.FieldText, Expr: "r.\"text\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"text\""},
			"main_category":    {Name: "main_category", Kind: querytable.FieldEnum, Expr: "r.\"main_category\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"main_category\""},
			"categories":       {Name: "categories", Kind: querytable.FieldTextArray, Expr: "r.\"categories\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"categories\""},
			"rules":            {Name: "rules", Kind: querytable.FieldTextArray, Expr: "r.\"rules\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"rules\""},
			"has_source":       {Name: "has_source", Kind: querytable.FieldBool, Expr: "r.\"has_source\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"has_source\""},
			"typed_message":    {Name: "typed_message", Kind: querytable.FieldBool, Expr: "r.\"typed_message\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"typed_message\""},
			"typed_words":      {Name: "typed_words", Kind: querytable.FieldNumber, Expr: "r.\"typed_words\"", Synthetic: false, ExpressionNumeric: true, Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"typed_words\""},
			"typed_share":      {Name: "typed_share", Kind: querytable.FieldNumber, Expr: "r.\"typed_share\"", Synthetic: false, ExpressionNumeric: true, AggregateOps: []string{}, Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"typed_share\""},
			"other_words":      {Name: "other_words", Kind: querytable.FieldNumber, Expr: "r.\"other_words\"", Synthetic: false, ExpressionNumeric: true, Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"other_words\""},
			"pasted_words":     {Name: "pasted_words", Kind: querytable.FieldNumber, Expr: "r.\"pasted_words\"", Synthetic: false, ExpressionNumeric: true, Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"pasted_words\""},
			"copied_words":     {Name: "copied_words", Kind: querytable.FieldNumber, Expr: "r.\"copied_words\"", Synthetic: false, ExpressionNumeric: true, Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"copied_words\""},
			"prompt_words":     {Name: "prompt_words", Kind: querytable.FieldNumber, Expr: "r.\"prompt_words\"", Synthetic: false, ExpressionNumeric: true, Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"prompt_words\""},
			"machine_words":    {Name: "machine_words", Kind: querytable.FieldNumber, Expr: "r.\"machine_words\"", Synthetic: false, ExpressionNumeric: true, Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"machine_words\""},
			"quoted_words":     {Name: "quoted_words", Kind: querytable.FieldNumber, Expr: "r.\"quoted_words\"", Synthetic: false, ExpressionNumeric: true, Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"quoted_words\""},
			"resent_words":     {Name: "resent_words", Kind: querytable.FieldNumber, Expr: "r.\"resent_words\"", Synthetic: false, ExpressionNumeric: true, Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"resent_words\""},
			"template_words":   {Name: "template_words", Kind: querytable.FieldNumber, Expr: "r.\"template_words\"", Synthetic: false, ExpressionNumeric: true, Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"template_words\""},
			"attachment_words": {Name: "attachment_words", Kind: querytable.FieldNumber, Expr: "r.\"attachment_words\"", Synthetic: false, ExpressionNumeric: true, Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"attachment_words\""},
			"harness_words":    {Name: "harness_words", Kind: querytable.FieldNumber, Expr: "r.\"harness_words\"", Synthetic: false, ExpressionNumeric: true, Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"harness_words\""},
			"automated_words":  {Name: "automated_words", Kind: querytable.FieldNumber, Expr: "r.\"automated_words\"", Synthetic: false, ExpressionNumeric: true, Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"automated_words\""},
			"words":            {Name: "words", Kind: querytable.FieldNumber, Expr: "r.\"words\"", Synthetic: false, ExpressionNumeric: true, Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"words\""},
			"chars":            {Name: "chars", Kind: querytable.FieldNumber, Expr: "r.\"chars\"", Synthetic: false, ExpressionNumeric: true, Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"chars\""},
			"message_count":    {Name: "message_count", Kind: querytable.FieldNumber, Expr: "r.\"message_count\"", Synthetic: false, ExpressionNumeric: true, Groupable: func() *bool { v := true; return &v }(), ServerFilter: true, Sortable: true, SortExpr: "r.\"message_count\""},
			"title":            {Name: "title", Kind: querytable.FieldText, Expr: "r.\"title\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"title\""},
			"repository_name":  {Name: "repository_name", Kind: querytable.FieldText, Expr: "r.\"repository_name\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"repository_name\""},
			"source_kind":      {Name: "source_kind", Kind: querytable.FieldEnum, Expr: "r.\"source_kind\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"source_kind\""},
			"provider":         {Name: "provider", Kind: querytable.FieldEnum, Expr: "r.\"provider\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"provider\""},
			"subagent":         {Name: "subagent", Kind: querytable.FieldBool, Expr: "r.\"subagent\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"subagent\""},
			"sender":           {Name: "sender", Kind: querytable.FieldText, Expr: "r.\"sender\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"sender\""},
			"conversation_id":  {Name: "conversation_id", Kind: querytable.FieldText, Expr: "r.\"conversation_id\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"conversation_id\""},
			"workspace_id":     {Name: "workspace_id", Kind: querytable.FieldText, Expr: "r.\"workspace_id\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"workspace_id\""},
			"work_id":          {Name: "work_id", Kind: querytable.FieldText, Expr: "r.\"work_id\"", Synthetic: false, ServerFilter: true, Sortable: true, SortExpr: "r.\"work_id\""},
		},
		DefaultSort:  []querytable.OrderBy{{Field: "sent_at", Dir: "desc", Nulls: "last"}},
		TiebreakSort: []querytable.OrderBy{{Field: "id", Dir: "asc"}},
	}
}
